name: Python application
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  
on:
  push:
  # schedule:
  #   - cron: '*/30 0-11 * * *'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.8' 

    - name: Install Dependence
      run: pip install requests langchain openai==0.28.1 tiktoken redis asyncio mutagen moviepy arxiv edge_tts bilibili-api-python nider Pillow==9.4.0

    - name: Run video.py
      run: python ./video.py


    
   
